### ISSUE TITLE
Multiple shots created

### ISSUE THREAD

**Issue by MunWolf** [CodingTrain/Asteroids#25]
If a ship dies and you shoot with your new ship both the new ship and the place where your old ship died create bullets.

**Comment by meiamsome** [comment]
This has already been fixed I think, can you try again?

**Comment by MunWolf** [comment]
Yeah, sorry it happened while I was testing #12 didnt happen on the actual branch

**Comment by LeastCreative** [comment]
just needed to reset the key listeners when the ship dies. that was a pretty cool update by the way showed me some things about javascript i never really understood

**Comment by MunWolf** [comment]
Glad to help you learn new things :)
