### ISSUE TITLE
Ship seems to rotate around awkward point

### ISSUE THREAD

**Issue by LeastCreative** [CodingTrain/Asteroids#26]
When you steer the ship around it seems like it almost rotates around the front of the ship just slightly. Almost like a shopping cart or something. Maybe there is a way to draw the triangle a bit ahead of the point of rotation?

**Comment by kwichmann** [comment]
I actually noticed this during the video. It shouldn't be too hard to change that by altering ship.render()

**Comment by MunWolf** [comment]
This needs to be closed as it has been fixed.
